<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-11-16 13:27
=======
# Generated by Django 4.1.2 on 2024-07-24 05:41
>>>>>>> f8a15b119148db1c7a40fb2171c0b76fddc1dadd

import baseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=baseapp.models.get_image_title_name, verbose_name='Изображение 269x230'),
        ),
    ]
